spring:
  application:
    name: empleados-mysql
  batch:
    jdbc.initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbempleados
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: izai
    password: vanegas
